// Kauniaisten katufaktat — kulttuuri, historia ja maamerkit.
window.HKI_FACTS = {
"Asematie": "Kauniaisten koko olemassaolo alkaa tästä kadusta: rantaradan asema avattiin 1900-luvun alussa, ja huvilakaupunki rakennettiin aseman ympärille. Asematie on yhä kaupungin selkäranka idästä länteen.",
"Kauniaistentie": "Kaupungin pääkatu, jonka varrella ovat kaupungintalo, kirkko ja Kauppakeskus Grani. Jos granilainen sanoo \"keskustassa\", hän tarkoittaa jotakin sadan metrin säteellä tästä kadusta.",
"Kavallintie": "Kavallin alue kaupungin itälaidalla oli pitkään peltoa ja huviloita. Katu kaartaa Gallträskin itäpuolelta kohti Helsingintietä ja on yksi kaupungin pisimmistä.",
"Bredantie": "Nimi tulee Bredan tilasta, joka näkyy edelleen Villa Bredan nimessä. Katu vetää kaupungin länsiosan halki ja on Kauniaisten vilkkaimpia asuinkatuja.",
"Bembölentie": "Katu johtaa kohti Bembölen vanhaa kylää Espoon puolella, jossa on toiminut kahvila vanhassa kruunun postitalossa. Kauniaisissa tie on samalla kaupungin läntinen sisääntulo.",
"Kasavuorentie": "Nousee Kasavuorelle, jonka nimi kertoo vanhasta vartiotulien perinteestä: kasa oli mäenlaella poltettu merkkituli. Nykyään mäellä on koulukeskus ja lukio.",
"Mäntymäentie": "Mäntymäki on Kauniaisten klassinen huvila-alue, jonka nimi kuvaa maastoa tarkasti: kalliota ja mäntyä. Kadun varrella toimii Mäntymäen koulu.",
"Kylpyläntie": "Muistuttaa ajasta, jolloin Kauniainen markkinoi itseään terveellisenä havumetsäkaupunkina ja alueella toimi parantola. Raikas ilma oli 1900-luvun alun myyntivaltti.",
"Urheilutie": "Kaupungin liikuntakeskittymä: uimahalli, palloiluhalli ja keskusurheilukenttä ovat kaikki tämän kadun varrella. Granin urheiluseurat GrIFK ja Riento täyttävät ne iltaisin.",
"Stenbergintie": "Kuuluu Kauniaisten henkilönimikatujen sarjaan, joilla muistetaan kauppalan alkuaikojen vaikuttajia. Kadun päässä avautuu Kasavuoren rinne.",
"Yrjö Liipolan tie": "Nimetty kuvanveistäjä Yrjö Liipolan mukaan. Kauniaisissa on kokonainen taiteilijoiden ja kirjailijoiden mukaan nimetty katujen ryhmä — harvinaista näin pienessä kaupungissa.",
"Mikael Lybeckin tie": "Kirjailija Mikael Lybeck oli suomenruotsalaisen kirjallisuuden keskeisiä nimiä. Katu kuuluu Kauniaisten kirjailijakatujen joukkoon kaupungin länsiosassa.",
"Magnus Hagelstamin tie": "Magnus Hagelstam oli kustantaja ja kulttuurivaikuttaja; nimi elää myös Hagelstamska skolanissa. Katu kertoo kaupungin kaksikielisestä sivistysperinnöstä.",
"Marcus Collinin kuja": "Taidemaalari Marcus Collin oli suomalaisen ekspressionismin uranuurtaja. Kuja on pieni, mutta kuuluu kaupungin taiteilijanimien kokoelmaan.",
"Suokrouvintie": "Krouvi tarkoittaa vanhaa kyytikapakkaa, ja nimi viittaa suon laidassa sijainneeseen majataloon. Kauniaisissa on kaksi krouvinimeä vierekkäin.",
"Krouvikalliontie": "Toinen kaupungin krouvinimistä: kallio, jonka juurella oli aikanaan majapaikka matkalaisille. Alue on nykyään rauhallista pientaloasutusta.",
"Stockmannintie": "Nimi juontaa Stockmannin suvun huvilaan, jonka rauniot ovat yhä nähtävissä lähellä Kaunialaa. Yksi Kauniaisten hienoimmista kadonneista rakennuksista.",
"Jalmarinpolku": "Kauniaisissa on poikkeuksellinen joukko etunimikatuja — Jalmari, Elina, Svea, Britta, Anna — joita ei ole nimetty kuuluisuuksien vaan tavallisten ihmisten mukaan.",
"Torpantie": "Torppa oli maanomistajan mailla vuokralla ollut pientila. Nimi muistuttaa, että Kauniainen oli ennen huvilakaupunkia maatalousmaisemaa.",
"Torpankuja": "Torpantien pikkusisar. Kaupungin kujat ovat tyypillisesti umpiperiä, joissa asfaltti loppuu ja kallio alkaa.",
"Bredanniitynkuja": "Bredan niitty oli tilan heinämaa, joka kaavoitettiin asuinkäyttöön vasta kauppala-ajan lopulla. Niitty näkyy vain nimessä.",
"Stenberginkuja": "Haarautuu Stenbergintiestä Kasavuoren kylkeen. Kauniaisten katuverkko on täynnä tällaisia kadun ja sen kujan pareja.",
"Koivuhovintie": "Johtaa Koivuhovin seisakkeen suuntaan — Kauniaisten toinen juna-asema, joka on tosin Espoon puolella heti rajan takana.",
"Palokunnantie": "Kadun varrella toimii Grankulla FBK, kaupungin vapaaehtoinen palokunta. VPK-perinne on Kauniaisissa yhtä vanha kuin kauppala itse.",
"Kauppalantie": "Kauniainen oli kauppala vuosina 1920–1972, ja tämä katu kantaa sen statuksen nimeä. Kaupunkioikeudet tulivat vasta 1972.",
"Yhtiöntie": "Yhtiö tarkoittaa AB Grankullaa, huvilayhtiötä joka osti maat ja myi tonttien lisäksi ajatuksen puutarhakaupungista. Ilman sitä Kauniaista ei olisi.",
"Gresantie": "Vanha tilannimi kaupungin eteläosasta. Katu yhdistää keskustan Sepänkylän suuntaan ja on osa kaupungin alkuperäistä tieverkkoa.",
"Smedsintie": "Smedsby eli Sepänkylä oli sepän kylä — sama nimi kahdella kielellä. Kauniaisten kaksikielisyys näkyy juuri tällaisissa nimipareissa.",
"Ersintie": "Etunimestä johdettu katu Kauppalan alueella. Kaupungin eteläosan kadut ovat kapeita ja mutkaisia, koska ne kiertävät kalliot.",
"Jondalintie": "Jondal oli yksittäinen tila kaupungin eteläreunalla, ja nimi on säilynyt vain kadussa. Alue on yhä väljästi rakennettua.",
"Leantie": "Yksi kaupungin etunimikaduista. Lyhyt, mutkainen ja tyypillinen esimerkki siitä, miten Kauniaisissa tie taipuu maaston mukaan eikä toisin päin.",
"Helenankuja": "Etunimikuja Kauppalan alueella. Kauniaisten kaavoitus jätti tarkoituksella tonttien väliin metsäkaistaleita, mikä näkyy tällaisilla kujilla.",
"Kaikupolku": "Nimi on harvinaisen runollinen jopa Kauniaisille. Kaupungin nimistössä on paljon luonnon ääniin ja tunnelmiin viittaavia katuja.",
"Junghansinkuja": "Junghansin suku kuuluu kaupungin varhaisiin huvila-asukkaisiin, ja Villa Junghans seisoo yhä lähistöllä. Kuja on lyhyt mutta arvokas.",
"Tornikuja": "Nimi viittaa tornimaiseen rakennukseen tai maastonkohtaan. Kauniaisten korkein maamerkki on kuitenkin vesitorni Vesitorninpolun päässä.",
"Kylätie": "Muistuttaa Sepänkylän maalaiskyläajoista. Kauniainen ehti olla kylä ja kauppala ennen kuin siitä tuli Suomen pienin kaupunki pinta-alaltaan.",
"Laaksotie": "Kulkee kaupungin keskustan laaksomaisen kohdan poikki. Kauniaisten korkeuserot ovat pieniä mutta jatkuvia — pyöräilijä huomaa sen.",
"Kirkkotie": "Johtaa Kauniaisten kirkolle, joka on kaupungin arkkitehtonisia päänähtävyyksiä ja seurakuntaelämän keskus. Kirkon yhteydessä on myös kolumbaario.",
"Vanha Turuntie": "Osa historiallista Turun suuntaan kulkenutta maantietä, jonka juuret ovat keskiajan Kuninkaantiessä. Kauniaisten läpi on kulkenut liikennettä kauan ennen kaupunkia.",
"Akatemiantie": "Kauniaisissa on kokonainen akateemisten arvonimien katujen ryhmä: Akatemiantie, Kandidaatintie, Maisterintie, Dosentintie ja Tohtorinkuja. Kaupungin koulutustaso näkyy kartalla.",
"Oppilaskodintie": "Nimi kertoo alueella toimineesta oppilaskodista. Kauniainen on ollut poikkeuksellisen koulukeskeinen kaupunki koko historiansa ajan.",
"Pohjoinen Heikelintie": "Heikelin nimi kuuluu kauppalan alkuvuosien vaikuttajiin. Kadun eteläinen pari ja Heikelinkuja täydentävät kolmikon.",
"Eteläinen Heikelintie": "Pohjoisen Heikelintien vastapari. Kauniaisissa on useita pohjoinen–eteläinen -katupareja, mikä pienessä kaupungissa on yllättävän kunnianhimoista.",
"Heikelinkuja": "Kolmas Heikelin-nimi kaupungin kartalla. Kuja johtaa Gränkullin puolelle, kaupungin vanhimpaan huvilavyöhykkeeseen.",
"Lindstedtintie": "Henkilönimikatu Gallträskin pohjoispuolella. Alueen huvilatontit ovat kaupungin suurimpia ja puusto vanhinta.",
"Pohjoinen Suotie": "Suo kertoo alkuperäisestä maastosta: keskustan pohjoispuolella oli kosteikkoa, joka kuivattiin rakentamisen tieltä.",
"Eteläinen Suotie": "Pohjoisen Suotien pari. Kadun nimi on ainoa jälki siitä, että tässä oli ennen märkää maata.",
"Alppitie": "Nimi on optimistinen: kyse on Kauniaisten mittapuulla jyrkästä kalliorinteestä. Talvella katu on kaupungin epävirallinen liukumäki.",
"Rantamajantie": "Vie Gallträskin rantaan, jossa on ollut kesämajoja ja saunoja. Järvi on kaupungin oma keskuspuisto.",
"Petaksentie": "Petas oli tila kaupungin pohjoislaidalla; nimi elää myös Café Petaksessa. Alue on Kauniaisten metsäisintä osaa.",
"Siestankuja": "Pieni kuja kaupungin pohjoisosassa. Kauniaisten pohjoisreuna vaihtuu lähes huomaamatta Espoon Lippajärveksi.",
"Silmukka": "Nimi kuvaa katua täsmällisesti: se tekee silmukan ja palaa takaisin. Kauniaisten kaavassa on useita tällaisia umpilenkkejä.",
"Venevalkamantie": "Johtaa Gallträskin venevalkamaan, jossa toimii Gallträsk Segelsällskap — järvi on niin pieni, että purjehdus vaatii taitoa eikä tuulta.",
"Richardinkuja": "Etunimikuja Gränkullin alueella. Nimeämistapa on peräisin kauppala-ajalta, jolloin kadut nimettiin usein tonttien myyjien ja ostajien mukaan.",
"Helsingintie": "Kaupungin itäinen sisääntulo ja vanha yhteys Helsinkiin. Nimi on suoraviivainen: tästä mennään kaupunkiin.",
"Maisterintie": "Kuuluu akateemisten arvonimien katujen ryhmään yhdessä Kandidaatintien ja Dosentintien kanssa. Maisterinkuja jatkaa samaa teemaa.",
"Forsellesintie": "Nimetty von Forsellesin suvun mukaan, joka kuuluu Kauniaisten varhaisiin maanomistajiin. Katu kulkee Sansinpellon suunnassa.",
"Mariantie": "Etunimikatu kaupungin itälaidalla. Kavallin puoli rakentui myöhemmin kuin keskusta, ja se näkyy väljemmässä kaavassa.",
"Kandidaatintie": "Akateemisen katusarjan nuorin arvonimi. Kandidaatinkuja haarautuu samasta risteyksestä — Kauniaisissa jopa kujat ovat suorittaneet tutkinnon.",
"Dosentintie": "Yksi kaupungin akateemisista kaduista. Nimeämisperiaate kertoo enemmän Kauniaisten itseymmärryksestä kuin mikään tilasto.",
"Puutarhatie": "Nimi on suora viittaus puutarhakaupunki-ideaan, jolle Kauniainen perustettiin: tontit isoja, puut säästetään, kadut kaartavat.",
"Juusintie": "Vanha tilannimi kaupungin itäosassa. Kavallin ja Juusin pellot olivat viljelyksessä vielä 1900-luvun puolivälissä.",
"Fasaaninpolku": "Kuuluu Kauniaisten metsästys- ja eläinaiheisten katujen sarjaan yhdessä Riekontien ja Linnustajantien kanssa.",
"Martankuja": "Etunimikuja Kavallin alueella. Kaupungin itäosan kadut on nimetty järjestelmällisemmin kuin vanhan keskustan mutkat.",
"Riekontie": "Riekko on tunturikanalintu, jota Kauniaisissa ei ole koskaan nähty — nimi kuuluu alueen lintuteemaan, ei havaintoihin.",
"Kerankuja": "Keran nimi tulee naapurin teollisuusalueelta, joka on nykyään yksi pääkaupunkiseudun suurimmista rakennushankkeista.",
"Siirinkuja": "Pieni etunimikuja itäisessä Kauniaisissa. Alueen kujat päättyvät poikkeuksetta kääntöpaikkaan ja kalliomännikköön.",
"Niinimäki": "Niini eli lehmuksen kuori oli arvokas raaka-aine köysille ja mattoihin. Mäkinimet ovat Kauniaisten yleisin nimityyppi.",
"Kandidaatinkuja": "Akateemisen katusarjan pienin jäsen. Kauniaisten kartalla voi kirjaimellisesti kulkea kandidaatista dosenttiin kolmessa korttelissa.",
"Ingankuja": "Etunimikuja Kavallin puolella. Kauniaisten etunimikadut ovat lähes aina kujia — pääkadut saivat arvokkaampia nimiä.",
"Kavallinrinne": "Kavallin alueen rinnekatu. Kaupungin itäosassa maasto nousee kohti Kavallinmäkeä, josta on parhaat näkymät yli kaupungin.",
"Signenkuja": "Signe on ruotsinkielinen etunimi, ja kuja kuuluu kaupungin kaksikieliseen nimiperinteeseen. Kauniaisissa jokaisella kadulla on nimi molemmilla kielillä.",
"Anna-muorin tie": "Kaupungin herkullisimmin nimetty katu: muori tarkoittaa vanhaa emäntää. Nimi viittaa paikalla asuneeseen naiseen, jonka etunimi riitti osoitteeksi.",
"Thurmanin puistotie": "Thurmanin nimi näkyy myös Thurmaninaukiossa keskustan sydämessä. Puistotie on kaupungin edustavimpia katuja.",
"Thurmaninaukio": "Kauniaisten oma tori ja aukio aseman kulmalla: kirjasto, kauppakeskus ja kirkko ovat kaikki muutaman minuutin päässä.",
"Promenadi": "Keskustan kävelyakseli, jonka nimi on lainattu suoraan ranskasta. Kaupungin ainoa katu, jolla kävely on virallisesti pääasia.",
"Käsityönkatu": "Lyhyt kävelykatu keskustassa, jonka nimi viittaa alueen pienyrittäjyyteen ja käsityöperinteeseen.",
"Teinikuja": "Nimi kertoo koulujen läheisyydestä: Kauniaisten kouluverkko on tiheä ja kävelymatkan päässä keskustasta.",
"Läntinen Koulupolku": "Yksi kahdesta koulupolusta keskustassa. Kauniaisissa lapset kävelevät kouluun — kaupunki on niin pieni, ettei muuta tarvita.",
"Ratapolku": "Kulkee rantaradan vieressä. Junarata halkaisee Kauniaisen kahtia, ja radan ylitys on kaupungin arjen tärkein logistinen kysymys."
};
