// Gatufakta för Grankulla — kultur, historia och landmärken.
window.HKI_FACTS_SV = {
"Asematie": "Hela Grankullas existens börjar med denna gata: stationen vid kustbanan öppnades i början av 1900-talet, och villastaden byggdes runt den. Stationsvägen är fortfarande stadens ryggrad från öst till väst.",
"Kauniaistentie": "Stadens huvudgata, med stadshuset, kyrkan och köpcentret Grani längs vägen. Säger en granibo \"i centrum\" menar han något inom hundra meter från denna gata.",
"Kavallintie": "Kavallområdet i stadens östra kant var länge åkrar och villor. Gatan svänger öster om Gallträsk mot Helsingforsvägen och är en av stadens längsta.",
"Bredantie": "Namnet kommer från Breda gård, som ännu lever kvar i namnet Villa Breda. Gatan går genom stadens västra del och är en av Grankullas livligaste bostadsgator.",
"Bembölentie": "Gatan leder mot den gamla byn Bemböle på Esbosidan, där ett kafé verkat i det gamla kronopostiljonhuset. I Grankulla är vägen samtidigt stadens västra infart.",
"Kasavuorentie": "Stiger upp på Kasaberget, vars namn berättar om gamla vårdkasar: en kasa var en signaleld som tändes på bergstoppen. I dag finns skolcentrum och gymnasium på berget.",
"Mäntymäentie": "Tallbacka är Grankullas klassiska villaområde, och namnet beskriver terrängen exakt: berg och tall. Längs gatan verkar Mäntymäen koulu.",
"Kylpyläntie": "Påminner om tiden då Grankulla marknadsförde sig som en hälsosam barrskogsstad och ett sanatorium verkade i området. Friska luften var ett försäljningsargument i början av 1900-talet.",
"Urheilutie": "Stadens idrottskoncentration: simhall, bollhall och centralidrottsplan ligger alla vid denna gata. Granis föreningar GrIFK och Riento fyller dem om kvällarna.",
"Stenbergintie": "Hör till Grankullas personnamnsgator, som hedrar köpingens tidiga påverkare. I gatans ände öppnar sig Kasabergets sluttning.",
"Yrjö Liipolan tie": "Uppkallad efter skulptören Yrjö Liipola. I Grankulla finns en hel grupp gator namngivna efter konstnärer och författare — ovanligt i en så liten stad.",
"Mikael Lybeckin tie": "Författaren Mikael Lybeck var en central gestalt i den finlandssvenska litteraturen. Gatan hör till Grankullas författargator i stadens västra del.",
"Magnus Hagelstamin tie": "Magnus Hagelstam var förläggare och kulturpåverkare; namnet lever också i Hagelstamska skolan. Gatan vittnar om stadens tvåspråkiga bildningsarv.",
"Marcus Collinin kuja": "Konstnären Marcus Collin var en pionjär inom den finländska expressionismen. Gränden är liten men hör till stadens samling av konstnärsnamn.",
"Suokrouvintie": "En krog var ett gammalt skjutshåll, och namnet syftar på ett värdshus vid mossens kant. I Grankulla ligger två krognamn sida vid sida.",
"Krouvikalliontie": "Det andra av stadens krognamn: ett berg med ett härbärge för resande vid foten. I dag är området stillsam småhusbebyggelse.",
"Stockmannintie": "Namnet härstammar från familjen Stockmanns villa, vars ruiner ännu syns nära Kaunialaområdet. En av Grankullas finaste försvunna byggnader.",
"Jalmarinpolku": "Grankulla har en ovanlig mängd förnamnsgator — Hjalmar, Elina, Svea, Britta, Anna — namngivna inte efter kändisar utan efter helt vanliga människor.",
"Torpantie": "Ett torp var ett småbruk på arrende hos en jordägare. Namnet påminner om att Grankulla var jordbrukslandskap före villastaden.",
"Torpankuja": "Torpvägens lillasyster. Stadens gränder slutar typiskt i en vändplan där asfalten tar slut och berget börjar.",
"Bredanniitynkuja": "Bredas äng var gårdens hömark, som planlades för bostäder först i slutet av köpingstiden. Ängen syns bara i namnet.",
"Stenberginkuja": "Grenar av från Stenbergsvägen mot Kasaberget. Grankullas gatunät är fullt av sådana par av gata och gränd.",
"Koivuhovintie": "Leder mot Björkgård hållplats — Grankullas andra tågstation, som visserligen ligger på Esbosidan strax bakom gränsen.",
"Palokunnantie": "Vid gatan verkar Grankulla FBK, stadens frivilliga brandkår. FBK-traditionen i Grankulla är lika gammal som köpingen själv.",
"Kauppalantie": "Grankulla var köping åren 1920–1972, och denna gata bär den statusens namn. Stadsrättigheterna kom först 1972.",
"Yhtiöntie": "Bolaget syftar på AB Grankulla, villabolaget som köpte marken och sålde både tomter och idén om en trädgårdsstad. Utan det fanns inget Grankulla.",
"Gresantie": "Ett gammalt gårdsnamn i stadens södra del. Gatan förbinder centrum med Smedsby och hör till stadens ursprungliga vägnät.",
"Smedsintie": "Smedsby var smedens by — samma namn på två språk. Grankullas tvåspråkighet syns just i sådana namnpar.",
"Ersintie": "En gata med förnamnsursprung i Köpingsområdet. Stadens södra gator är smala och krokiga eftersom de går runt bergen.",
"Jondalintie": "Jondal var en enskild gård i stadens södra kant, och namnet har bevarats bara i gatan. Området är ännu glest byggt.",
"Leantie": "En av stadens förnamnsgator. Kort, krokig och ett typiskt exempel på hur vägen i Grankulla böjer sig efter terrängen och inte omvänt.",
"Helenankuja": "Förnamnsgränd i Köpingsområdet. Grankullas planläggning lämnade medvetet skogsremsor mellan tomterna, vilket syns på sådana gränder.",
"Kaikupolku": "Namnet är ovanligt poetiskt även för Grankulla. Stadens namnskick har många gator som syftar på naturens ljud och stämningar.",
"Junghansinkuja": "Familjen Junghans hör till stadens tidiga villainvånare, och Villa Junghans står ännu i närheten. Gränden är kort men värdig.",
"Tornikuja": "Namnet syftar på en tornliknande byggnad eller terrängformation. Grankullas högsta landmärke är dock vattentornet vid Vesitorninpolku.",
"Kylätie": "Påminner om Smedsbys tid som lantlig by. Grankulla hann vara by och köping innan det blev Finlands minsta stad till ytan.",
"Laaksotie": "Går genom den dalliknande sänkan i stadens centrum. Grankullas höjdskillnader är små men oavbrutna — cyklisten märker det.",
"Kirkkotie": "Leder till Grankulla kyrka, ett av stadens arkitektoniska huvudsevärdheter och centrum för församlingslivet. I anslutning finns också ett kolumbarium.",
"Vanha Turuntie": "En del av den historiska landsvägen mot Åbo, med rötter i medeltidens Kungsväg. Trafik har gått genom Grankulla långt före staden fanns.",
"Akatemiantie": "I Grankulla finns en hel grupp gator med akademiska titlar: Akademivägen, Kandidatvägen, Magistervägen, Docentvägen och Tohtorinkuja. Stadens utbildningsnivå syns på kartan.",
"Oppilaskodintie": "Namnet berättar om ett elevhem som verkat i området. Grankulla har varit en exceptionellt skolcentrerad stad under hela sin historia.",
"Pohjoinen Heikelintie": "Namnet Heikel hör till köpingens tidiga påverkare. Gatans södra motsvarighet och Heikelsgränden fullbordar trion.",
"Eteläinen Heikelintie": "Norra Heikelvägens motpart. I Grankulla finns flera norra–södra-par av gator, vilket i en så liten stad är förvånansvärt ambitiöst.",
"Heikelinkuja": "Det tredje Heikel-namnet på stadens karta. Gränden leder mot Grankullasidan, stadens äldsta villazon.",
"Lindstedtintie": "Personnamnsgata norr om Gallträsk. Områdets villatomter är stadens största och trädbeståndet det äldsta.",
"Pohjoinen Suotie": "Mossen berättar om den ursprungliga terrängen: norr om centrum fanns våtmark som torrlades för bebyggelsen.",
"Eteläinen Suotie": "Norra Mossavägens par. Gatans namn är det enda spåret av att här en gång var blöt mark.",
"Alppitie": "Namnet är optimistiskt: det handlar om en med grankullamått brant bergssluttning. På vintern är gatan stadens inofficiella pulkabacke.",
"Rantamajantie": "Går ner till Gallträsks strand, där det funnits sommarstugor och bastur. Sjön är stadens egen centralpark.",
"Petaksentie": "Petas var en gård i stadens norra kant; namnet lever också i Café Petas. Området är Grankullas mest skogbevuxna del.",
"Siestankuja": "En liten gränd i stadens norra del. Grankullas norra kant övergår nästan omärkligt i Esbos Klappträsk.",
"Silmukka": "Namnet beskriver gatan exakt: den gör en ögla och kommer tillbaka. Grankullas plan har flera sådana slutna slingor.",
"Venevalkamantie": "Leder till Gallträsks båtlänning, där Gallträsk Segelsällskap verkar — sjön är så liten att segling kräver skicklighet snarare än vind.",
"Richardinkuja": "Förnamnsgränd i Grankullaområdet. Namnskicket härstammar från köpingstiden, då gator ofta fick namn efter tomternas säljare och köpare.",
"Helsingintie": "Stadens östra infart och den gamla förbindelsen till Helsingfors. Namnet är rakt på sak: härifrån åker man till staden.",
"Maisterintie": "Hör till gruppen med akademiska titlar tillsammans med Kandidatvägen och Docentvägen. Maisterinkuja fortsätter samma tema.",
"Forsellesintie": "Uppkallad efter släkten von Forselles, som hör till Grankullas tidiga jordägare. Gatan går i riktning mot Sansinpelto.",
"Mariantie": "Förnamnsgata i stadens östra kant. Kavallsidan byggdes senare än centrum, och det syns i en glesare plan.",
"Kandidaatintie": "Den yngsta titeln i den akademiska gatuserien. Kandidatgränden grenar av från samma korsning — i Grankulla har till och med gränderna en examen.",
"Dosentintie": "En av stadens akademiska gator. Namngivningsprincipen säger mer om Grankullas självbild än någon statistik.",
"Puutarhatie": "Namnet är en direkt hänvisning till trädgårdsstadsidén som Grankulla grundades på: stora tomter, bevarade träd, svängda gator.",
"Juusintie": "Ett gammalt gårdsnamn i stadens östra del. Kavalls och Juus åkrar odlades ännu i mitten av 1900-talet.",
"Fasaaninpolku": "Hör till Grankullas serie av jakt- och djurnamn tillsammans med Ripvägen och Linnustajantie.",
"Martankuja": "Förnamnsgränd i Kavallområdet. Stadens östra gator är namngivna mer systematiskt än gamla centrums krokar.",
"Riekontie": "Ripan är en fjällfågel som aldrig setts i Grankulla — namnet hör till områdets fågeltema, inte till observationer.",
"Kerankuja": "Namnet Kera kommer från industriområdet i nabolaget, i dag ett av huvudstadsregionens största byggprojekt.",
"Siirinkuja": "En liten förnamnsgränd i östra Grankulla. Områdets gränder slutar undantagslöst i en vändplan och en bergstallskog.",
"Niinimäki": "Bast, det vill säga lindens bark, var ett värdefullt råmaterial för rep och mattor. Backnamn är Grankullas vanligaste namntyp.",
"Kandidaatinkuja": "Den minsta medlemmen i den akademiska gatuserien. På Grankullas karta kan man bokstavligen gå från kandidat till docent i tre kvarter.",
"Ingankuja": "Förnamnsgränd på Kavallsidan. Grankullas förnamnsgator är nästan alltid gränder — huvudgatorna fick värdigare namn.",
"Kavallinrinne": "Kavallområdets brinkgata. I stadens östra del stiger terrängen mot Kavallbacken, varifrån man har den bästa utsikten över staden.",
"Signenkuja": "Signe är ett svenskt förnamn, och gränden hör till stadens tvåspråkiga namntradition. I Grankulla har varje gata ett namn på båda språken.",
"Anna-muorin tie": "Stadens läckraste gatunamn: mor betyder gammal husmor. Namnet syftar på en kvinna som bott på platsen och vars förnamn räckte som adress.",
"Thurmanin puistotie": "Namnet Thurman syns också i Thurmansplatsen i centrums hjärta. Allén är en av stadens mest representativa gator.",
"Thurmaninaukio": "Grankullas eget torg vid stationshörnet: bibliotek, köpcentrum och kyrka ligger alla några minuter bort.",
"Promenadi": "Centrums gångaxel, vars namn är lånat direkt från franskan. Stadens enda gata där promenerandet officiellt är huvudsaken.",
"Käsityönkatu": "En kort gågata i centrum, vars namn syftar på områdets småföretagande och hantverkstradition.",
"Teinikuja": "Namnet berättar om skolornas närhet: Grankullas skolnät är tätt och ligger inom gångavstånd från centrum.",
"Läntinen Koulupolku": "En av två skolstigar i centrum. I Grankulla går barnen till skolan — staden är så liten att inget annat behövs.",
"Ratapolku": "Går längs kustbanan. Järnvägen delar Grankulla i två delar, och att korsa spåret är vardagens viktigaste logistiska fråga."
};
